title: Error
description: Life often requires some excitement, joy, and anticipation.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://zhui.dev

author:
  name: Mr. Error 追
  email: "error@zhui.dev"

twitter:
  username: RiverOnVenus

permalink: /:year-:month/:title
timezone: Asia/Shanghai

favicon: /assets/img/favicon.ico

google_analytics: G-S5EFHRZ8YD

#disqus_shortname:
#gitalk:
giscus: true
#cusdis:
    #app_id:

user:
  name: Mr. Error 追
  pic: /assets/img/avatar.jpg
  picAlt: "RiverOnVenus"
  job: Life often requires some excitement, joy, and anticipation.
  search: true
  about: true
  feed: true
  key: true

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-spaceship

jekyll-spaceship:
  element-processor:
    css:
      - a:
          props:
            loading: lazy

exclude:
  - README.md
  - LICENSE
  - github

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
